name: schedule
on: 
  workflow_dispatch:
    inputs:
      data:
        description: 'enter value'
        type: choice
        required: true
        options:
          - A
          - B
      
  schedule:
  - cron: '*/5 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule job every 10 sec
        run: |
          date
          echo Data is ${{inputs.data}}
    
  
