name: schedule
on: 
  pull_request_target: 
    branches:
      - main
  schedule:
  - cron: '*/5 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule job every 10 sec
        run: |
          date
          echo Data is ${{inputs.data}}
    
  
